import { InvoiceData } from '../types.ts';

export const SAMPLE_INVOICE_DEV: InvoiceData = {
  id: 'sample-inv-001',
  title: 'Full-Stack Web App Development',
  invoiceNumber: 'INV-2026-084',
  issueDate: '2026-09-15',
  dueDate: '2026-10-15',
  poNumber: 'PO-98231',
  status: 'pending',
  currency: 'USD',
  logoUrl: '',
  sender: {
    name: 'Apex Studio Labs Inc.',
    email: 'billing@apexstudiolabs.com',
    phone: '+1 (555) 234-8901',
    address: '742 Montgomery St, Suite 400',
    cityStateZip: 'San Francisco, CA 94111',
    country: 'United States',
    taxId: 'US-94-3829103',
  },
  client: {
    name: 'Horizon Retail Technologies',
    email: 'ap@horizonretail.io',
    phone: '+1 (555) 876-5432',
    address: '1200 Innovation Parkway, Floor 8',
    cityStateZip: 'Austin, TX 78759',
    country: 'United States',
    taxId: 'TX-74-8891234',
  },
  shippingAddress: '1200 Innovation Parkway, Receiving Dock B, Austin, TX 78759',
  showShipping: false,
  items: [
    {
      id: 'item-1',
      description: 'Single-Page Web Application Frontend (React 19 + TypeScript + Tailwind)',
      quantity: 45,
      rate: 110,
    },
    {
      id: 'item-2',
      description: 'Client-side PDF Generator Module with Custom Print Engines',
      quantity: 18,
      rate: 120,
    },
    {
      id: 'item-3',
      description: 'UI/UX Interactive System Design & Accessibility Audit (WCAG AA)',
      quantity: 12,
      rate: 95,
    },
    {
      id: 'item-4',
      description: 'Cloud Static Site Deployment & GitHub Pages CI/CD Pipeline Setup',
      quantity: 6,
      rate: 130,
    },
  ],
  discountType: 'percentage',
  discountValue: 5,
  taxRate: 8.25,
  taxLabel: 'Sales Tax',
  shippingFee: 0,
  amountPaid: 2000,
  payment: {
    bankName: 'Silicon Valley National Bank',
    accountName: 'Apex Studio Labs Inc. Operating',
    accountNumber: '•••••••• 8829',
    routingOrSwift: 'SVNBUS6SXXX / 121000358',
    paymentLink: 'https://pay.stripe.com/demo_apex_invoice_084',
    notes: 'Thank you for partnering with Apex Studio Labs! Please include invoice number INV-2026-084 on wire transfers.',
    terms: 'Payment is due within 30 days of issue. Overdue accounts are subject to a 1.5% monthly late finance fee.',
  },
  template: 'modern',
  accentColor: '#2563eb', // royal blue
};

export const SAMPLE_INVOICE_CONSULTING: InvoiceData = {
  id: 'sample-inv-002',
  title: 'Strategic Management Consulting',
  invoiceNumber: 'INV-2026-092',
  issueDate: '2026-09-20',
  dueDate: '2026-10-05',
  poNumber: 'PO-44102',
  status: 'draft',
  currency: 'EUR',
  logoUrl: '',
  sender: {
    name: 'Vanguard Strategy Partners',
    email: 'invoicing@vanguardpartners.eu',
    phone: '+44 20 7946 0912',
    address: '25 Bank Street, Canary Wharf',
    cityStateZip: 'London E14 5JP',
    country: 'United Kingdom',
    taxId: 'GB 982 4510 88',
  },
  client: {
    name: 'Nordic CleanEnergy AB',
    email: 'finance@nordicclean.se',
    phone: '+46 8 123 4567',
    address: 'Kungsgatan 44',
    cityStateZip: '111 35 Stockholm',
    country: 'Sweden',
    taxId: 'SE556123456701',
  },
  showShipping: false,
  items: [
    {
      id: 'item-1',
      description: 'Q3 Enterprise Digital Transformation Roadmap & Architecture Review',
      quantity: 1,
      rate: 4500,
    },
    {
      id: 'item-2',
      description: 'Executive Stakeholder Workshops & Technical Risk Assessment',
      quantity: 16,
      rate: 220,
    },
    {
      id: 'item-3',
      description: 'Zero-Trust Cloud Governance Framework Documentation',
      quantity: 1,
      rate: 1800,
    },
  ],
  discountType: 'fixed',
  discountValue: 500,
  taxRate: 20,
  taxLabel: 'VAT',
  shippingFee: 0,
  amountPaid: 0,
  payment: {
    bankName: 'Barclays International Commercial Banking',
    accountName: 'Vanguard Strategy Partners Ltd',
    accountNumber: 'GB82 BARC 2004 1538 9201 44',
    routingOrSwift: 'BARCGB22',
    paymentLink: 'https://settle.vanguardpartners.eu/inv-092',
    notes: 'Please remit payment directly via SEPA or BACS transfer using invoice reference INV-2026-092.',
    terms: 'Net 15 days upon receipt of invoice.',
  },
  template: 'executive',
  accentColor: '#0f766e', // teal
};

export const BLANK_INVOICE_FACTORY = (): InvoiceData => ({
  id: `inv-${Date.now()}`,
  title: 'New Service Invoice',
  invoiceNumber: `INV-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 900) + 100)}`,
  issueDate: new Date().toISOString().split('T')[0],
  dueDate: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
  status: 'draft',
  currency: 'USD',
  logoUrl: '',
  sender: {
    name: 'Your Company Name',
    email: 'contact@yourcompany.com',
    phone: '+1 (555) 000-0000',
    address: '123 Business Way',
    cityStateZip: 'City, State 12345',
    country: 'Country',
    taxId: '',
  },
  client: {
    name: 'Client Company Name',
    email: 'accounts@clientcompany.com',
    phone: '+1 (555) 999-9999',
    address: '456 Customer Ave',
    cityStateZip: 'Metro, State 67890',
    country: 'Country',
    taxId: '',
  },
  showShipping: false,
  items: [
    {
      id: `item-${Date.now()}-1`,
      description: 'Professional Services / Development',
      quantity: 1,
      rate: 100,
    },
  ],
  discountType: 'percentage',
  discountValue: 0,
  taxRate: 0,
  taxLabel: 'Tax',
  shippingFee: 0,
  amountPaid: 0,
  payment: {
    bankName: '',
    accountName: '',
    accountNumber: '',
    routingOrSwift: '',
    paymentLink: '',
    notes: 'Thank you for your business!',
    terms: 'Payment is due within 30 days of issue.',
  },
  template: 'modern',
  accentColor: '#2563eb',
});
